-- db/supabase_schema.sql
-- Run this in your Supabase SQL Editor to create the tables required for the Clinic Receptionist App.

-- Patients table
CREATE TABLE IF NOT EXISTS public.patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_number TEXT NOT NULL,
    name TEXT NOT NULL,
    gender TEXT CHECK (gender IN ('male', 'female', 'other')),
    dob DATE,
    age INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_patients_contact ON public.patients(contact_number);

-- Doctors table
CREATE TABLE IF NOT EXISTS public.doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    specialization TEXT NOT NULL,
    status TEXT CHECK (status IN ('active', 'inactive')) DEFAULT 'active'
);

CREATE INDEX IF NOT EXISTS idx_doctors_spec ON public.doctors(specialization);

-- Visits table
CREATE TABLE IF NOT EXISTS public.visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES public.patients(id),
    doctor_id BIGINT NOT NULL REFERENCES public.doctors(id),
    visit_date DATE NOT NULL,
    visit_time TIME NOT NULL,
    token_number INTEGER,
    status TEXT CHECK (status IN ('waiting', 'in_progress', 'completed', 'cancelled')) DEFAULT 'waiting',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_visits_doctor_date ON public.visits(doctor_id, visit_date);
